[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'markonm/traces.vim'

[[plugins]]
repo = 'skanehira/translate.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = "release"

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'alvan/vim-closetag'

[[plugins]]
repo = 'lambdalisue/suda.vim'

[[plugins]]
repo = 'kana/vim-altercmd'
hook_add = '''
  call altercmd#load()
  AlterCommand sudawrite SudaWrite
  AlterCommand sudaread SudaRead
'''

[[plugins]]
repo = 'lambdalisue/fern.vim'
